experiment_name: "swin_base_384_final_hard_answer"
paths:
  data_dir: "data_final_hard_answer"
model:
  backbone: "swin_base_patch4_window12_384.ms_in22k_ft_in1k"
  image_size: 384
  pooling: "gap"
  pretrained_file: "swin_base_patch4_window12_384.ms_in22k_ft_in1k.pth"
train:
  batch_size: 16
  epochs: 15
  base_lr: 0.0005
  backbone_lr_factor: 0.1
  pos_weight_mode: "none"
  label_smoothing: 0.05
ema:
  enabled: true
  decay: 0.999
augmentation:
  coarse_dropout:
    enabled: true
    max_holes: 4
    max_height: 48
    max_width: 48
