experiment_name: "swinv2_base_384_minimal_pseudo0818_no_guarded"
paths:
  dataset_dir: "data_final_hard_answer"
model:
  backbone: "swinv2_base_window12to24_192to384.ms_in22k_ft_in1k"
  pretrained_file: "swinv2_base_window12to24_192to384.ms_in22k_ft_in1k.pth"
  image_size: 384
  pooling: "gap"
train:
  amp: true
  amp_dtype: "bfloat16"
inference:
  batch_size: 32
test:
  tta_enabled: false
